### ISSUE TITLE
docker-entrypoint-initdb.d scripts are relauched at restart 

### ISSUE THREAD

**Issue by icrc-fdeniger** [bitnami/bitnami-docker-mysql#107]
To check it you can reuse: https://github.com/bitnami/bitnami-docker-mysql/issues/106

The issue:
in the documentation, it's explained that  `/bitnami/mysql/data` should be declared as a volume.
But in the code, we can see that `/bitnami/mysql` is used to saved the file `.user_scripts_initialized`
https://github.com/bitnami/bitnami-docker-mysql/blob/18d76ea3388bbf1d465efe8f0b8559db7aef5f2d/5.7/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L334

Shall we persist `/bitnami/mysql` or the code should be changed ?

**Comment by juan131** [comment]
Hi @icrc-fdeniger 

You're 100% right! That's something we missed when the recommended mount point to persist data was changed, see:

- https://github.com/bitnami/bitnami-docker-mysql#5723-r52-and-8012-r34

That flag (`.user_scripts_initialized`) shouldn't be created at "DB_VOLUME_DIR" but "DB_DATA_DIR" instead. Would you like to create a PR to address this? I can do it for you otherwise.
