### ISSUE TITLE
Init scripts not getting loaded from files\docker-entrypoint-initdb.d directory

### ISSUE THREAD

**Issue by Akhilesh2909** [bitnami/bitnami-docker-mysql#111]
Hi Team,

I am using init scripts to initialize DDLs from docker-entrypoint-initdb.d directory using helm bitnami/mysql helm chart. For the first time, DDLs are loaded as expected. In case if we have updated DDLs or we include new DDL, those updated or new DDLs are not getting reflected. 
I can see, new scripts are copied to pod directory /docker-entrypoint-initdb.d, but its not getting executed.

It seems this is happening because of pvc created by helm chart, which will not be deleted on helm uninstall(which is expected).

As per logs, seems existing pvc is used, and revised DDLs are not added to pvc and not getting executed.

My requirement is to execute scripts from /docker-entrypoint-initdb.d every-time helm chart is installed.

Please assist, how this requirement be achieved.

Thanks in Advance!

**Steps to reproduce the issue:**

1. Helm install command with one DDL script in files/docker-entrypoint-initdb.d directory.
2. Helm uninstall
3. Add a new DDL to files/docker-entrypoint-initdb.d in chart.
4. Helm install

Regards
Akhilesh

**Comment by miguelaeh** [comment]
Hi @Akhilesh2909 ,
Thank you very much for your suggestion. 
We already have an internal task to improve that and be able to execute the scripts with every initialization. I am afraid that currently it is not supported, but it is something many users requested in the past.
I have added this case to the task to notify you one we address it.
Regards.

**Comment by Akhilesh2909** [comment]
Thanks for Reply Miguel.
Hope we will have requested feature added soon.

Regards
Akhilesh

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
