### ISSUE TITLE
Master master replication

### ISSUE THREAD

**Issue by milis92** [bitnami/bitnami-docker-mysql#43]
Awesome image guys. Is there any way this can be extended for Master master replication?

**Comment by juan131** [comment]
Hi @f0restgump92 

Thanks for this suggestion! I also think it could be a very interesting option to offer a master-master replication solution. We are evaluating this solution and we will notify you about any decision we take regarding this feature.

**Comment by ilevac** [comment]
Any news?

**Comment by andresbono** [comment]
Hi @ilevac, we provide the [MariaDB Galera container](https://github.com/bitnami/bitnami-docker-mariadb-galera) that can be configured as a multi-master database cluster.

We also maintain the Helm Chart for this application: https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera

Hope these assets are what you are looking for!

**Comment by ilevac** [comment]
@andresbono 
Unfortunately I need mysql 5.7 for my specific application.

**Comment by andresbono** [comment]
I'm afraid that we don't support MySQL with multi master configuration, just MariaDB. None of the MariaDB versions that we distribute is compatible with your application?

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
