### ISSUE TITLE
Mysql container is exiting with code 1

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/bitnami-docker-mysql#79]
I am using a new t2.large aws EC2 machine (Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-04763b3055de4860b (64-bit x86)

docker-compose.yml:

version: '2.4'
services:
  mysql:
    container_name: mysql
    image: bitnami/mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: test
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3306:3306"
    volumes:
      - '/tmp/mysql:/bitnami/mysql/data'
    restart: "no"

~      
Logs:

mysql    |  11:59:12.66 
mysql    |  11:59:12.66 Welcome to the Bitnami mysql container
mysql    |  11:59:12.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql    |  11:59:12.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql    |  11:59:12.66 Send us your feedback at containers@bitnami.com
mysql    |  11:59:12.67 
mysql    |  11:59:12.67 INFO  ==> ** Starting MySQL setup **
mysql    |  11:59:12.70 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql    |  11:59:12.70 INFO  ==> Initializing mysql database
mysql    |  11:59:12.71 INFO  ==> Installing database
mysql exited with code 1

Is there any other log file, from where I can check the reason behind this exit ?

**Comment by dgomezleon** [comment]
Hi @pankaj-dahiya,

Thank you for using our containers. You are getting that error message because the container can't mount the `/tmp/mysql` directory.

Since it follows the non-root user approach, the user 1001 needs read/write permissions in the /tmp/mysql folder so it can be mounted and used. Can you modify the permissions in your local folder and try to launch the container again?

> sudo chown -R 1001 /tmp/mysql

In order to obtain a more verbose output, you can use the `BITNAMI_DEBUG` env vble in your docker-compose.yml

```
    environment:
      - MYSQL_ROOT_PASSWORD="Hello@123"
      - MYSQL_DATABASE="test"
      - MYSQL_USER="user1"
      - MYSQL_PASSWORD="pass1"
      - BITNAMI_DEBUG=true
```

That way, you should see something like this:
```
mysql_1  | mysqld: Can't create/write to file '/bitnami/mysql/data/is_writable' (Errcode: 13 - Permission denied)
mysql_1  | 2019-10-23T14:39:10.711506Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
mysql_1  | 2019-10-23T14:39:10.711552Z 0 [ERROR] Aborting
mysql_1  |
```

I hope it helps

**Comment by pankaj-dahiya** [comment]
I have changed the user to root and it is working fine now.
